import re

RULES = [
    {"id":"SEC-001","name":"Hardcoded Secret / API Key","severity":"HIGH",
     "pattern":re.compile(r'(api_key|apikey|secret|password|token|private_key)\s*=\s*["\'][^"\']{6,}["\']',re.I),
     "description":"Hardcoded credentials found in source code.",
     "attack":"Credential theft / unauthorized API access"},
    {"id":"SEC-002","name":"SQL Injection","severity":"HIGH",
     "pattern":re.compile(r'(query|sql|execute|cursor\.execute)\s*\(.*?\+.*?(input|request|param|user)',re.I),
     "description":"User input directly concatenated into SQL query.",
     "attack":"SQL Injection leading to data breach or DB takeover"},
    {"id":"SEC-003","name":"Cross-Site Scripting (XSS)","severity":"HIGH",
     "pattern":re.compile(r'(innerHTML|outerHTML|document\.write)\s*=\s*.*(req\.|request\.|params\.|query\.)',re.I),
     "description":"Unsanitized user input injected into DOM.",
     "attack":"XSS allowing session hijacking or defacement"},
    {"id":"SEC-004","name":"Eval of User Input","severity":"HIGH",
     "pattern":re.compile(r'eval\s*\(.*?(req\.|request\.|input|param|user)',re.I),
     "description":"eval() called with user-controlled data.",
     "attack":"Remote code execution"},
    {"id":"SEC-005","name":"Insecure Random","severity":"MEDIUM",
     "pattern":re.compile(r'\bMath\.random\(\)|random\.random\(\)',re.I),
     "description":"Non-cryptographic random for security context.",
     "attack":"Predictable token/session generation"},
    {"id":"SEC-006","name":"Exposed Secret in Env File","severity":"HIGH",
     "pattern":re.compile(r'(OPENAI_API_KEY|DATABASE_URL|JWT_SECRET|SECRET_KEY)\s*=\s*.+',re.I),
     "description":"Secret keys found in environment or config file.",
     "attack":"Credential exposure if committed to repo"},
    {"id":"SEC-007","name":"Prototype Pollution","severity":"MEDIUM",
     "pattern":re.compile(r'__proto__|constructor\[.*?prototype',re.I),
     "description":"Potential prototype pollution via object manipulation.",
     "attack":"Privilege escalation via prototype tampering"},
    {"id":"SEC-008","name":"Insecure CORS","severity":"MEDIUM",
     "pattern":re.compile(r'Access-Control-Allow-Origin.*\*|cors\(\s*\{.*origin.*\*',re.I),
     "description":"Wildcard CORS policy allows any origin.",
     "attack":"Cross-origin data theft"},
    {"id":"SEC-009","name":"Path Traversal","severity":"HIGH",
     "pattern":re.compile(r'(readFile|readFileSync|open|path\.join)\s*\(.*?(req\.|request\.|params\.|query\.)',re.I),
     "description":"User input in file path without sanitization.",
     "attack":"Directory traversal to read arbitrary files"},
    {"id":"SEC-010","name":"Command Injection","severity":"HIGH",
     "pattern":re.compile(r'(exec|spawn|system|child_process)\s*\(.*?(req\.|input|param|user)',re.I),
     "description":"User input passed to shell command.",
     "attack":"Remote command execution on server"},
    {"id":"SEC-011","name":"Insecure Deserialization","severity":"HIGH",
     "pattern":re.compile(r'(pickle\.loads|yaml\.load\s*\((?!.*Loader)|unserialize)\s*\(',re.I),
     "description":"Unsafe deserialization of untrusted data.",
     "attack":"RCE via crafted payload"},
    {"id":"SEC-012","name":"Open Redirect","severity":"MEDIUM",
     "pattern":re.compile(r'(res\.redirect|window\.location)\s*\(.*?(req\.|request\.|params\.|query\.)',re.I),
     "description":"User-controlled redirect destination.",
     "attack":"Phishing via trusted domain"},
    {"id":"SEC-013","name":"Weak Hash Algorithm","severity":"MEDIUM",
     "pattern":re.compile(r'\bhashlib\.(md5|sha1)\s*\(|\bmd5\s*\(|\bsha1\s*\(',re.I),
     "description":"MD5 or SHA-1 used — both are cryptographically broken.",
     "attack":"Hash collision / brute-force of stored credentials"},
    {"id":"SEC-014","name":"Debug Error Exposure","severity":"LOW",
     "pattern":re.compile(r'(console\.error|traceback\.print_exc)\s*\(.*?(err|exception|e)\b',re.I),
     "description":"Raw error or stack trace may leak internals.",
     "attack":"Information disclosure aiding targeted attacks"},
    {"id":"SEC-015","name":"JWT None Algorithm","severity":"HIGH",
     "pattern":re.compile(r'algorithm\s*=\s*["\']none["\']',re.I),
     "description":"JWT signed with 'none' disables signature verification.",
     "attack":"Token forgery — any payload accepted as valid"},
]
